@echo off
REM BAT que compila els fitxers java de la PAC4
REM (c) Joan Antoni Dominguez, Cristian Ceballos, Ivan Margarit  i Marc Pérez
@ echo on

set classpath=.;C:\UOC\15-16\TDP\PAC4\PAC4_TDP_2015\codi\src\edu\*;

javac uoc\tdp\pac4\beans\Actividad.java
javac uoc\tdp\pac4\beans\Adminstrador.java
javac uoc\tdp\pac4\beans\Alumno.java
javac uoc\tdp\pac4\beans\Asistencia.java
javac uoc\tdp\pac4\beans\Aula.java
javac uoc\tdp\pac4\beans\AuxiliarCombo.java
javac uoc\tdp\pac4\beans\Centro.java
javac uoc\tdp\pac4\beans\Grupo.java
javac uoc\tdp\pac4\beans\IdentifiableObject.java
javac uoc\tdp\pac4\beans\Matricula.java
javac uoc\tdp\pac4\beans\PersonalAcademico.java
javac uoc\tdp\pac4\beans\PeticionRecurso.java
javac uoc\tdp\pac4\beans\PeticionRecursoDetalle.java
javac uoc\tdp\pac4\beans\Profesor.java
javac uoc\tdp\pac4\beans\Recurso.java
javac uoc\tdp\pac4\beans\Usuario.java
javac uoc\tdp\pac4\client\PnlMain.java
javac uoc\tdp\pac4\client\conexion\PnlConsultaMatricula.java
javac uoc\tdp\pac4\client\conexion\PnlConsultaLogin.java
javac uoc\tdp\pac4\client\conexion\PnlMarcaAsistencia.java
javac uoc\tdp\pac4\client\conexion\PnlMuestraBibliografia.java
javac uoc\tdp\pac4\client\conexion\PnlMuestraPlanDocente.java
javac uoc\tdp\pac4\client\conexion\PnlSolicitaMatricula.java
javac uoc\tdp\pac4\client\estadisticas\PnlFiltroActividades.java
javac uoc\tdp\pac4\client\estadisticas\PnlFiltroPersonalAcademico.java
javac uoc\tdp\pac4\client\estadisticas\PnlFiltroProfesor.java
javac uoc\tdp\pac4\client\estadisticas\PnlListadoAlumno.java
javac uoc\tdp\pac4\client\estadisticas\PnlListadoPersonalAcademico.java
javac uoc\tdp\pac4\client\estadisticas\PnlListadoProfesor.java
javac uoc\tdp\pac4\client\gestion\PnlAsistencia.java
javac uoc\tdp\pac4\client\gestion\PnlGroup.java
javac uoc\tdp\pac4\client\gestion\PnlGroupGestor.java
javac uoc\tdp\pac4\client\gestion\PnlMatricula.java
javac uoc\tdp\pac4\client\gestion\PnlMatriculaGestor.java
javac uoc\tdp\pac4\client\mantenimiento\PnlMantenimientoActividades.java
javac uoc\tdp\pac4\client\mantenimiento\PnlMantenimientoActividadGestor.java
javac uoc\tdp\pac4\client\mantenimiento\PnlMantenimientoAulaGestor.java
javac uoc\tdp\pac4\client\mantenimiento\PnlMantenimientoAulas.java
javac uoc\tdp\pac4\client\mantenimiento\PnlMantenimientoRecursoGestor.java
javac uoc\tdp\pac4\client\mantenimiento\PnlMantenimientoRecursos.java
javac uoc\tdp\pac4\client\mantenimiento\PnlMantenimientoUsuarioGestor.java
javac uoc\tdp\pac4\client\mantenimiento\PnlMantenimientoUsuarios.java
javac uoc\tdp\pac4\dao\GestorActividad.java
javac uoc\tdp\pac4\dao\GestorAlumno.java
javac uoc\tdp\pac4\dao\GestorAsistencia.java
javac uoc\tdp\pac4\dao\GestorAulas.java
javac uoc\tdp\pac4\dao\GestorCentro.java
javac uoc\tdp\pac4\dao\GestorConexion.java
javac uoc\tdp\pac4\dao\GestorDisco.java
javac uoc\tdp\pac4\dao\GestorGrupo.java
javac uoc\tdp\pac4\dao\GestorMatricula.java
javac uoc\tdp\pac4\dao\GestionPeticionRecurso.java
javac uoc\tdp\pac4\dao\GestorProfesor.java
javac uoc\tdp\pac4\dao\GestorRecursos.java
javac uoc\tdp\pac4\dao\GestorUsuario.java
javac uoc\tdp\pac4\exceptions\ApplicationAlreadyExistsException.java
javac uoc\tdp\pac4\exceptions\AssistanceAlreadyCountedException.java
javac uoc\tdp\pac4\exceptions\DuplicatedRequestException.java
javac uoc\tdp\pac4\exceptions\eAssistenciaEsception.java
javac uoc\tdp\pac4\exceptions\GroupAlreadyCountedException.java
javac uoc\tdp\pac4\exceptions\GroupAlreadyExistsException.java
javac uoc\tdp\pac4\exceptions\GroupNotEmptyException.java
javac uoc\tdp\pac4\exceptions\NoGroupFountException.java
javac uoc\tdp\pac4\exceptions\NoRolesException.java
javac uoc\tdp\pac4\exceptions\NotAvailableProfessorException.java
javac uoc\tdp\pac4\exceptions\StudentAssistanceAlreadyCountedException.java
javac uoc\tdp\pac4\exceptions\StudentNotExistsException.java
javac uoc\tdp\pac4\exceptions\TooManyRequestException.java
javac uoc\tdp\pac4\exceptions\GestioDeFacturasException.java
javac uoc\tdp\pac4\remote\Conexion.java
javac uoc\tdp\pac4\remote\ConexionImpl.java
javac uoc\tdp\pac4\remote\Estadisticas.java
javac uoc\tdp\pac4\remote\EstadisticasImpl.java
javac uoc\tdp\pac4\remote\GestAcademica.java
javac uoc\tdp\pac4\remote\GestAcademicaImpl.java
javac uoc\tdp\pac4\remote\Mantenimiento.java
javac uoc\tdp\pac4\remote\MantenimientoImpl.java
javac uoc\tdp\pac4\remote\tdpLanguageUtils.java
javac uoc\tdp\pac4\server\Servidor.java
javac uoc\tdp\pac4\util\ComboItem.java
javac uoc\tdp\pac4\util\DateTimeUtils.java
javac uoc\tdp\pac4\util\FieldLimit.java
javac uoc\tdp\pac4\util\LanguageUtils.java
javac uoc\tdp\pac4\util\NumericUtils.java
javac uoc\tdp\pac4\util\StringUtils.java
javac uoc\tdp\pac4\eAcademiaEU.java


rmic uoc.tdp.pac4.server.impl.RemotoImpl