package edu.uoc.tdp.pac4.client.mantenimiento;

import edu.uoc.tdp.pac4.beans.Usuario;
import edu.uoc.tdp.pac4.remote.Mantenimiento;
import edu.uoc.tdp.pac4.util.LanguageUtils;
import edu.uoc.tdp.pac4.exceptions.NoRolesException;

import java.rmi.RemoteException;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**********************************************************************
 ******************** @author JavaBeginers - Cristian******************
 *********************************************************************/

public class PnlMantenimientoUsuarios extends javax.swing.JDialog 
{
    private Mantenimiento      manager;
    private LanguageUtils      language;
    private ArrayList<Usuario> usuarios;
    private boolean dofilter   = false;
    
    private Usuario activeUser;
    
   
    /**
     * Creates new form PnlGroupGestor
     */
    public PnlMantenimientoUsuarios(java.awt.Frame parent, boolean modal, Mantenimiento manager, LanguageUtils language, Usuario activeUser) {
        super(parent, modal);
            
        this.language       = language;
        this.activeUser     = activeUser;
        this.manager        = manager;
        
        initComponents();
        setLocationRelativeTo(null);
        prepararTextos();
        setCombos();
        listarUsuarios();
    }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        cmdClose = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        comboRol = new javax.swing.JComboBox();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        fldNombre = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        lblRol = new javax.swing.JLabel();
        fldApellidos = new javax.swing.JTextField();
        lblApellidos = new javax.swing.JLabel();
        cmdFilter = new javax.swing.JButton();
        cmdClearFilter = new javax.swing.JButton();
        btnExplore = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jToolBar1.setRollover(true);

        cmdClose.setText("Cerrar");
        cmdClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCloseActionPerformed(evt);
            }
        });

        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblData);

        btnAdd.setText("Nuevo");
        btnAdd.setFocusable(false);
        btnAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdd.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnEdit.setText("Editar");
        btnEdit.setFocusable(false);
        btnEdit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEdit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setText("Eliminar");
        btnDelete.setFocusable(false);
        btnDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDelete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        lblNombre.setText("Nombre");

        lblRol.setText("rol");

        lblApellidos.setText("Apellidos");

        cmdFilter.setText("Filtrar");
        cmdFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdFilterActionPerformed(evt);
            }
        });

        cmdClearFilter.setText("Limpiar Filtro");
        cmdClearFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdClearFilterActionPerformed(evt);
            }
        });

        btnExplore.setText("Explorar");
        btnExplore.setFocusable(false);
        btnExplore.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExplore.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExplore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExploreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdd)
                        .addGap(0, 0, 0)
                        .addComponent(btnEdit)
                        .addGap(0, 0, 0)
                        .addComponent(btnDelete)
                        .addGap(18, 18, 18)
                        .addComponent(btnExplore)
                        .addGap(20, 20, 20)
                        .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(cmdClose))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(lblRol, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboRol, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblNombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fldApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmdClearFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmdFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnAdd)
                        .addComponent(btnEdit)
                        .addComponent(btnDelete)
                        .addComponent(btnExplore)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre)
                    .addComponent(lblRol)
                    .addComponent(fldApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblApellidos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdFilter)
                    .addComponent(cmdClearFilter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmdClose)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

//Establece los textos segun idioma seleccionado      
   private void prepararTextos() {
       
       this.setTitle(language.getProperty("mantenimiento.usermain.title"));
       this.btnAdd.setText         (language.getProperty("mantenimiento.Nueva"));
       this.btnEdit.setText        (language.getProperty("mantenimiento.Editar"));
       this.btnDelete.setText      (language.getProperty("mantenimiento.Eliminar"));
       this.btnExplore.setText     (language.getProperty("mantenimiento.Ver"));
       this.cmdClose.setText       (language.getProperty("mantenimiento.usermain.back"));
       this.lblRol.setText         (language.getProperty("mantenimiento.usermain.tipo"));
       this.lblNombre.setText        (language.getProperty("mantenimiento.usermain.name"));
       this.lblApellidos.setText     (language.getProperty("mantenimiento.usermain.surname"));
       this.cmdFilter.setText      (language.getProperty("mantenimiento.usermain.dofilter"));
       this.cmdClearFilter.setText (language.getProperty("mantenimiento.usermain.clearfilter"));
       this.fldNombre.setText("");
       this.fldApellidos.setText("");
   }

//Carga los combos de la pantalla 
   private void setCombos() {
        /*
         * Intentamos capturar los posibles roles definidos por la base de datos para añadirlos
         * al combobox. Si no se puede, no podremos abrir este panel, pues algo pasa con la connexión
         * a la DB o al rmi.
         */
        

    }
   
//Se escoge 'Alta de Usuario'  
   private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
           PnlMantenimientoUsuarioGestor form = new PnlMantenimientoUsuarioGestor(null, true ,manager, language, "Add", 0);
           form.setLocationRelativeTo(null);
           form.setVisible(true);
           listarUsuarios();
   }//GEN-LAST:event_btnAddActionPerformed

//Se escoge 'Edición de Usuario'  
   private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
       //No hay fila seleccionada
      if (tblData.getSelectedRow() < 0)
      {
         JOptionPane.showMessageDialog(null,
                                       language.getProperty("mantenimiento.msg.sele.usuario"),
                                       language.getProperty("app.title"),
                                       JOptionPane.WARNING_MESSAGE);
         return;
      }
      //Hay fila seleccionada
      Usuario usuario = usuarios.get(tblData.getSelectedRow());
      PnlMantenimientoUsuarioGestor form = new PnlMantenimientoUsuarioGestor(null, true, manager, language, "Edit", usuario.getId());
      form.setLocationRelativeTo(null);
      form.setVisible(true);
      listarUsuarios();
   }//GEN-LAST:event_btnEditActionPerformed

//Cerrar el Formulario
   private void cmdCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCloseActionPerformed

      // Cierra el formulario
      this.dispose();

   }//GEN-LAST:event_cmdCloseActionPerformed

//Se escoge Desactivar Usuario
   private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
      //No hay fila seleccionada
      if (tblData.getSelectedRow() < 0)
      {
         JOptionPane.showMessageDialog(null,
                                       language.getProperty("mantenimiento.msg.sele.usuario"),
                                       language.getProperty("app.title"),
                                       JOptionPane.WARNING_MESSAGE);
         return;
      }
      //Hay fila seleccionada
      Usuario usuario = usuarios.get(tblData.getSelectedRow());
      
      //El usuario seleccionado es el propio usuario
      if (usuario.getId() == this.activeUser.getId()) {
          JOptionPane.showMessageDialog(null,
                                       language.getProperty("mantenimiento.err.deown"),
                                       language.getProperty("app.title"),
                                       JOptionPane.WARNING_MESSAGE);
         return;
      }
      
      //Se desactivará usuario si se responde afirmativamente
      Object[] options = {language.getProperty("opt.si"), language.getProperty("opt.no")};
      int reply = JOptionPane.showOptionDialog(this, language.getProperty("mantenimientomsg.dele.usuario"), 
                                               language.getProperty("app.title"), JOptionPane.YES_NO_OPTION, 
                                               JOptionPane.QUESTION_MESSAGE, null, options, usuario);
      if (reply == 0) {
        try {
            manager.deleteUsuario(usuario.getId());
        
      }
      catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, 
                                          language.getProperty("err.sql") + "\n" + language.getProperty("err.detail") + ":\n\n" + ex.getMessage(), 
                                          language.getProperty("app.title"), 
                                          JOptionPane.ERROR_MESSAGE);
      }
      catch (Exception ex) {
            JOptionPane.showMessageDialog(null, 
                                          language.getProperty("err.generic") + "\n" + language.getProperty("err.detail") + ":\n\n" + ex.getMessage(), 
                                          language.getProperty("app.title"), 
                                          JOptionPane.ERROR_MESSAGE);
      }
      
      listarUsuarios();
      }
   }//GEN-LAST:event_btnDeleteActionPerformed

//Botón Filtrar  
    private void cmdFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdFilterActionPerformed
        // TODO add your handling code here:
        if (!this.comboRol.getSelectedItem().toString().equals(language.getProperty("rol.all")) ||
            !this.fldNombre.getText().equals("") || !this.fldApellidos.getText().equals("")) {
            this.dofilter = true;
            listarUsuarios();
        }
    }//GEN-LAST:event_cmdFilterActionPerformed

//Botón Limpiar Filtro
    private void cmdClearFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdClearFilterActionPerformed
        // TODO add your handling code here:
        this.comboRol.setSelectedIndex(0);
        this.fldNombre.setText("");
        this.fldApellidos.setText("");
        this.dofilter = false;
        listarUsuarios();
    }//GEN-LAST:event_cmdClearFilterActionPerformed

//Consultar Usuario 
    private void btnExploreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExploreActionPerformed
        // No hay fila seleccionada
        if (tblData.getSelectedRow() < 0)
      {
         JOptionPane.showMessageDialog(null,
                                       language.getProperty("mantenimiento.msg.sele.usuario"),
                                       language.getProperty("app.title"),
                                       JOptionPane.WARNING_MESSAGE);
         return;
      }
      //Hay fila seleccionada
      Usuario usuario = usuarios.get(tblData.getSelectedRow());
      PnlMantenimientoUsuarioGestor form = new PnlMantenimientoUsuarioGestor(null, true, manager, language, "Explore", usuario.getId());
      form.setLocationRelativeTo(null);
      form.setVisible(true);
    }//GEN-LAST:event_btnExploreActionPerformed

//Cargar todas las Aulas
    private void todosUsuarios() throws SQLException, RemoteException, Exception {
        ArrayList<String> header = new ArrayList<String>();   // cabecera
      
        header.add(language.getProperty("mantenimiento.usermain.login"));
        header.add(language.getProperty("mantenimiento.usermain.DNI"));
        header.add(language.getProperty("mantenimiento.usermain.name"));
        header.add(language.getProperty("mantenimiento.usermain.surname"));
        header.add(language.getProperty("mantenimiento.usermain.rol"));
        
        String[][] gridData;
        
        usuarios = manager.getUsuarios();
        gridData = new String[usuarios.size()][5];
        
        int i = 0;
        for (Usuario usuario : usuarios) {
            gridData[i][0] = usuario.getLogin();
            gridData[i][1] = usuario.getNif();
            gridData[i][2] = usuario.getNombre();
            gridData[i][3] = usuario.getApellidos();
            gridData[i][4] = "" + usuario.getIdRol();
            i++;
        }
        
        this.tblData.setModel(new javax.swing.table.DefaultTableModel(gridData, header.toArray())
            {@Override public boolean isCellEditable(int row, int column)
                { return false; } 
            });
    }
    
    private void filtrarUsuarios() throws SQLException, RemoteException, Exception {
        ArrayList<String> header = new ArrayList<String>();   // cabecera
      
        header.add(language.getProperty("mantenimiento.usermain.login"));
        header.add(language.getProperty("mantenimiento.usermain.DNI"));
        header.add(language.getProperty("mantenimiento.usermain.name"));
        header.add(language.getProperty("mantenimiento.usermain.surname"));
        header.add(language.getProperty("mantenimiento.usermain.rol"));
      
        String[][] gridData;
        /*
        String rolDescriptor = "";
        if (!this.comboRol.getSelectedItem().toString().equals(language.getProperty("rol.all"))) {
            System.err.print(VariableDescriptors.get(this.comboRol.getSelectedItem().toString()).toString());
            usuarios = manager.getUsuariosByRolDesc(VariableDescriptors.get(this.comboRol.getSelectedItem().toString()).toString());
        }
        else {
            usuarios = manager.getUsuarios();
        }
        gridData = new String[usuarios.size()][5];
        
        int i = 0;
        for (Usuario usuario : usuarios) {
            System.err.print(this.fldApellidos.getText() + "\n");
            System.err.print(usuario.getPrimerApellido() + "\n");
            if ((this.fldNombre.getText().equals("")    || this.fldNombre.getText().equalsIgnoreCase(usuario.getNombre())) &&
                (this.fldApellidos.getText().equals("") || this.fldApellidos.getText().equalsIgnoreCase(usuario.getPrimerApellido())
                                                      || this.fldApellidos.getText().equalsIgnoreCase(usuario.getSegundoApellido()))) {
                gridData[i][0] = usuario.getLogin();
                gridData[i][1] = usuario.getNif();
                gridData[i][2] = usuario.getNombre();
                gridData[i][3] = usuario.getApellidos();
                gridData[i][4] = language.getProperty(this.RolesID.get(usuario.getIdRol()).toString());
                i++;
            }
        }
        
        this.tblData.setModel(new javax.swing.table.DefaultTableModel(gridData, header.toArray())
            {@Override public boolean isCellEditable(int row, int column)
                { return false; } 
            });*/
    }
    
   private void listarUsuarios()
   {
      try {
          if (!this.dofilter) {
              todosUsuarios();
          }
          else {
              filtrarUsuarios();
          }
      } 
      catch (SQLException ex)
      {
         JOptionPane.showMessageDialog(null, 
                                       language.getProperty("err.sql") + "\n" + language.getProperty("err.detail") + ":\n\n" + ex.getMessage(), 
                                       language.getProperty("app.title"), 
                                       JOptionPane.ERROR_MESSAGE);
      }
      catch (RemoteException ex)
      {
         JOptionPane.showMessageDialog(null, 
                                       language.getProperty("err.rmi") + "\n" + language.getProperty("err.detail") + ":\n\n" + ex.getMessage(), 
                                       language.getProperty("app.title"), 
                                       JOptionPane.ERROR_MESSAGE);

      }
      catch (Exception ex) 
      {
         JOptionPane.showMessageDialog(null, 
                                       language.getProperty("err.generic") + "\n" + language.getProperty("err.detail") + ":\n\n" + ex.getMessage(), 
                                       language.getProperty("app.title"), 
                                       JOptionPane.ERROR_MESSAGE);
      }
   }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnExplore;
    private javax.swing.JButton cmdClearFilter;
    private javax.swing.JButton cmdClose;
    private javax.swing.JButton cmdFilter;
    private javax.swing.JComboBox comboRol;
    private javax.swing.JTextField fldApellidos;
    private javax.swing.JTextField fldNombre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRol;
    private javax.swing.JTable tblData;
    // End of variables declaration//GEN-END:variables
}
