package edu.uoc.tdp.pac4.client.mantenimiento;

import edu.uoc.tdp.pac4.beans.Actividad;
import edu.uoc.tdp.pac4.beans.Usuario;
import edu.uoc.tdp.pac4.eAcademiaEU;
import edu.uoc.tdp.pac4.remote.Mantenimiento;
import edu.uoc.tdp.pac4.util.ComboItem;
import edu.uoc.tdp.pac4.util.DateTimeUtils;
import edu.uoc.tdp.pac4.util.LanguageUtils;
import java.rmi.RemoteException;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author eSupport Netbeans
 */
public class PnlMantenimientoActividades extends javax.swing.JDialog {

    private static final int ROL_ADMINISTRADOR = 1;
    private static final int ROL_SECRETARIA = 2;
    private static final int ROL_PROFESOR = 2;
    private static final int ROL_ALUMNO = 3;
    private List<ComboItem> tiposActividad;

    private final Mantenimiento manager;
    private final LanguageUtils language;
    private ArrayList<Actividad> actividades;
    private Usuario usuario;

    private boolean dofilter = false;

    /**
     * Creates new form PnlGroupGestor
     * @param parent
     * @param modal
     * @param manager
     * @param language
     * @param usuario
     */
    public PnlMantenimientoActividades(java.awt.Frame parent, boolean modal, Mantenimiento manager, LanguageUtils language, Usuario usuario) {

        super(parent, modal);
        this.language = language;
        this.manager = manager;
        this.usuario = usuario;
        initComponents();

        setLocationRelativeTo(null);

        addaptToPreferences();
        setTipoActividades();

        listData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        cmdClose = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        cmdFilter = new javax.swing.JButton();
        cmdClearFilter = new javax.swing.JButton();
        btnAsistencia = new javax.swing.JButton();
        lblFiltroTipoActividad = new javax.swing.JLabel();
        cboFiltroTipoActividad = new javax.swing.JComboBox();
        lblFiltroDateIni = new javax.swing.JLabel();
        fldFiltroDateIni = new javax.swing.JFormattedTextField();
        lblFiltroDateEnd = new javax.swing.JLabel();
        fldFiltroDateFin = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jToolBar1.setRollover(true);

        cmdClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/arrow-curve-180.png"))); // NOI18N
        cmdClose.setText("Cerrar");
        cmdClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCloseActionPerformed(evt);
            }
        });

        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblData);

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/projection-screen--plus.png"))); // NOI18N
        btnAdd.setText("Nuevo");
        btnAdd.setFocusable(false);
        btnAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdd.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/projection-screen--pencil.png"))); // NOI18N
        btnEdit.setText("Editar");
        btnEdit.setFocusable(false);
        btnEdit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEdit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/projection-screen--minus.png"))); // NOI18N
        btnDelete.setText("Eliminar");
        btnDelete.setFocusable(false);
        btnDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDelete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        cmdFilter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/refresh_002_16.gif"))); // NOI18N
        cmdFilter.setText("Filtrar");
        cmdFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdFilterActionPerformed(evt);
            }
        });

        cmdClearFilter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/eraser.png"))); // NOI18N
        cmdClearFilter.setText("Limpiar Filtro");
        cmdClearFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdClearFilterActionPerformed(evt);
            }
        });

        btnAsistencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/asistencia.png"))); // NOI18N
        btnAsistencia.setText("Asistencia");
        btnAsistencia.setFocusable(false);
        btnAsistencia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAsistencia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAsistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsistenciaActionPerformed(evt);
            }
        });

        lblFiltroTipoActividad.setText("Tipo de Actividad");

        cboFiltroTipoActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboFiltroTipoActividadActionPerformed(evt);
            }
        });

        lblFiltroDateIni.setText("Fecha Inicio");

        fldFiltroDateIni.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        fldFiltroDateIni.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        lblFiltroDateEnd.setText("Fecha Inicio");

        fldFiltroDateFin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        fldFiltroDateFin.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAsistencia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAdd)
                        .addGap(0, 0, 0)
                        .addComponent(btnEdit)
                        .addGap(0, 0, 0)
                        .addComponent(btnDelete)
                        .addGap(83, 83, 83)
                        .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(cmdClose))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblFiltroTipoActividad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboFiltroTipoActividad, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblFiltroDateIni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fldFiltroDateIni, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblFiltroDateEnd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fldFiltroDateFin, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81)))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmdClearFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmdFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnAdd)
                        .addComponent(btnEdit)
                        .addComponent(btnDelete)
                        .addComponent(btnAsistencia)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblFiltroDateEnd)
                        .addComponent(fldFiltroDateFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblFiltroDateIni)
                        .addComponent(fldFiltroDateIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblFiltroTipoActividad)
                        .addComponent(cboFiltroTipoActividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdFilter)
                    .addComponent(cmdClearFilter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmdClose)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addaptToPreferences() {

        this.setTitle(language.getProperty("mantenimiento.main.title") + ". "
                + language.getProperty("mantenimiento.main.curse"));

        this.setLabelsLanguage();

        //this.fldasistencia.setText("");
    }

    private void setLabelsLanguage() {
        this.btnAdd.setText(language.getProperty("mantenimiento.usermain.newUser"));
        this.btnEdit.setText(language.getProperty("mantenimiento.usermain.modUser"));
        this.btnDelete.setText(language.getProperty("mantenimiento.usermain.delUser"));
        this.cmdClose.setText(language.getProperty("mantenimiento.usermain.back"));

        this.lblFiltroTipoActividad.setText(language.getProperty("mantenimiento.actividad.tipo.actividad"));
        this.lblFiltroDateIni.setText(language.getProperty("mantenimiento.actividad.fechaini"));
        this.lblFiltroDateEnd.setText(language.getProperty("mantenimiento.actividad.fechaend"));

        this.cmdFilter.setText(language.getProperty("mantenimiento.usermain.dofilter"));
        this.cmdClearFilter.setText(language.getProperty("mantenimiento.usermain.clearfilter"));
    }

   private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed

       PnlMantenimientoActividadGestor form = new PnlMantenimientoActividadGestor(this, true, manager, language, "Add", 0, usuario);
       form.setLocationRelativeTo(null);
       form.setVisible(true);

       listData();
   }//GEN-LAST:event_btnAddActionPerformed

   private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed

       if (tblData.getSelectedRow() < 0) {
           JOptionPane.showMessageDialog(null,
                   language.getProperty("mantenimiento.msg.sele.actividad"),
                   language.getProperty("app.title"),
                   JOptionPane.WARNING_MESSAGE);
           return;
       }

       // Obtiene el ID de la actividad a editar
       Actividad actividad = actividades.get(tblData.getSelectedRow());

       PnlMantenimientoActividadGestor form = new PnlMantenimientoActividadGestor(null, true, manager, language, "Edit", actividad.getId(), usuario);
       form.setLocationRelativeTo(null);
       form.setVisible(true);

       listData();

   }//GEN-LAST:event_btnEditActionPerformed

   private void cmdCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCloseActionPerformed

       // Cierra el formulario
       this.dispose();

   }//GEN-LAST:event_cmdCloseActionPerformed

   private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

       if (tblData.getSelectedRow() < 0) {
           JOptionPane.showMessageDialog(null,
                   language.getProperty("mantenimiento.msg.sele.actividad"),
                   language.getProperty("app.title"),
                   JOptionPane.WARNING_MESSAGE);
           return;
       }

       Actividad actividad = actividades.get(tblData.getSelectedRow());

       Object[] options = {"Si", "No"};//NOi18
       int reply = JOptionPane.showOptionDialog(this, "quiere borrar actividad " + actividad.getTitol(), language.getProperty("app.title"), JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, actividad);
       if (reply == 0) {
           try {

               manager.deleteActividad(actividad.getId());

           } catch (SQLException ex) {
               JOptionPane.showMessageDialog(null,
                       language.getProperty("err.sql") + "\n" + language.getProperty("err.detail") + ":\n\n" + ex.getMessage(),
                       language.getProperty("app.title"),
                       JOptionPane.ERROR_MESSAGE);
           } catch (Exception ex) {
               JOptionPane.showMessageDialog(null,
                       language.getProperty("err.generic") + "\n" + language.getProperty("err.detail") + ":\n\n" + ex.getMessage(),
                       language.getProperty("app.title"),
                       JOptionPane.ERROR_MESSAGE);
           }

           listData();
       }
   }//GEN-LAST:event_btnDeleteActionPerformed

    private void cmdFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdFilterActionPerformed
        if (this.cboFiltroTipoActividad.getSelectedIndex() > 0) {
            this.dofilter = true;
            listData();
        }
        if (!this.fldFiltroDateIni.getText().equals("")) {
            this.dofilter = true;
            listData();
        }
        if (!this.fldFiltroDateFin.getText().equals("")) {
            this.dofilter = true;
            listData();
        }

    }//GEN-LAST:event_cmdFilterActionPerformed

    private void cmdClearFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdClearFilterActionPerformed
        // TODO add your handling code here:
        this.cboFiltroTipoActividad.setSelectedIndex(0);
        this.fldFiltroDateIni.setText("");
        this.fldFiltroDateFin.setText("");
        this.dofilter = false;
        listData();
    }//GEN-LAST:event_cmdClearFilterActionPerformed

    private void btnAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsistenciaActionPerformed
        if (tblData.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(null,
                    language.getProperty("mantenimiento.msg.sele.actividad"),
                    language.getProperty("app.title"),
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Obtiene el ID de la actividad
        Actividad actividad = actividades.get(tblData.getSelectedRow());

        PnlMantenimientoAsistenciaActividadGestor form = new PnlMantenimientoAsistenciaActividadGestor(null, true, manager, language, "Edit", actividad.getId(), usuario);
        form.setLocationRelativeTo(null);
        form.setVisible(true);

        listData();
    }//GEN-LAST:event_btnAsistenciaActionPerformed

    private void cboFiltroTipoActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboFiltroTipoActividadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboFiltroTipoActividadActionPerformed

    /**
     * Rellena la tabla de usuarios.
     */
    private void listFullActividadesData() throws SQLException, RemoteException, Exception {
        ArrayList<String> header = new ArrayList<String>();   // cabecera

        header.add(language.getProperty("mantenimiento.usermain.universidad"));
        header.add(language.getProperty("mantenimiento.usermain.tipo"));
        header.add(language.getProperty("mantenimiento.usermain.name"));
        header.add(language.getProperty("mantenimiento.actividad.fechaini"));
        header.add(language.getProperty("mantenimiento.actividad.fechaend"));

        String[][] gridData;
        if (usuario.getIdRol() == ROL_SECRETARIA) {
            actividades = manager.getActividadesByUniversidadId(usuario.getUniversidadId());
            gridData = new String[actividades.size()][5];
            int i = 0;
            for (Actividad actividad : actividades) {
                gridData[i][0] = getDescUniversidad(Math.toIntExact(actividad.getUniversitatId()));
                gridData[i][1] = getDescTipus(actividad.getTipus());
                gridData[i][2] = actividad.getTitol();
                gridData[i][3] = new SimpleDateFormat("dd/MM/YYYY").format(actividad.getDataInici());
                if(actividad.getDataFi()!=null) {
                    gridData[i][4] = new SimpleDateFormat("dd/MM/YYYY").format(actividad.getDataFi());
                } else {
                    gridData[i][4] = "Sin definir";
                }
                i++;
            }
        } else {
            gridData = new String[0][5];
        }

        //Modificamos la tabla para que no sea editable
        this.tblData.setModel(new DefaultTableModel(gridData, header.toArray()) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });
    }

    private void listFilteredActividadesData() throws SQLException, RemoteException, Exception {
        ArrayList<String> header = new ArrayList<String>();   // cabecera

        header.add(language.getProperty("mantenimiento.usermain.universidad"));
        header.add(language.getProperty("mantenimiento.usermain.tipo"));
        header.add(language.getProperty("mantenimiento.usermain.name"));
        header.add(language.getProperty("mantenimiento.actividad.fechaini"));
        header.add(language.getProperty("mantenimiento.actividad.fechaend"));

        String[][] gridData;

        actividades = manager.getActividadesByUniversidadId(usuario.getUniversidadId());
        gridData = new String[actividades.size()][5];

        int i = 0;
        boolean filtrar = false;
        for (Actividad actividad : actividades) {
            if (this.cboFiltroTipoActividad.getSelectedIndex() > 0) {
                int tipusActivitat = ((ComboItem) cboFiltroTipoActividad.getSelectedItem()).getId();
                if (actividad.getTipus() != tipusActivitat) {
                    filtrar = true;
                }
            }
            if (!fldFiltroDateIni.getText().equals("")) {
                if (actividad.getDataFi().getTime() < DateTimeUtils.strToDate(this.fldFiltroDateIni.getText()).getTime()) {
                    filtrar = true;
                }
            }
            if (!fldFiltroDateFin.getText().equals("")) {
                if (actividad.getDataInici().getTime() > DateTimeUtils.strToDate(this.fldFiltroDateFin.getText()).getTime()) {
                    filtrar = true;
                }
            }
            if (!filtrar) {
                gridData[i][0] = getDescUniversidad(Math.toIntExact(actividad.getUniversitatId()));
                gridData[i][1] = getDescTipus(actividad.getTipus());
                gridData[i][2] = actividad.getTitol();
                gridData[i][3] = new SimpleDateFormat("dd/MM/YYYY").format(actividad.getDataInici());
                if(actividad.getDataFi()!=null) {
                    gridData[i][4] = new SimpleDateFormat("dd/MM/YYYY").format(actividad.getDataFi());
                } else {
                    gridData[i][4] = language.getProperty("field.without.value");
                }
                i++;
            }
            filtrar = false;
        }

        this.tblData.setModel(new javax.swing.table.DefaultTableModel(gridData, header.toArray()));
    }

    private String getDescTipus(int tipusId) {

        switch (tipusId) {
            case Actividad.ACTIVIDAD_TIPO_CONGRESO_ID:
                return Actividad.getTipoActividadName(Actividad.ACTIVIDAD_TIPO_CONGRESO_ID, language);
            case Actividad.ACTIVIDAD_TIPO_JORNADA_ID:
                return Actividad.getTipoActividadName(Actividad.ACTIVIDAD_TIPO_JORNADA_ID, language);
            case Actividad.ACTIVIDAD_TIPO_MASTER_ID:
                return Actividad.getTipoActividadName(Actividad.ACTIVIDAD_TIPO_MASTER_ID, language);
            case Actividad.ACTIVIDAD_TIPO_CONFERENCIA_ID:
                return Actividad.getTipoActividadName(Actividad.ACTIVIDAD_TIPO_CONFERENCIA_ID, language);
            default:
                return "(-)";
        }

    }

    private String getDescUniversidad(int universidadId) {

        switch (universidadId) {
            case Actividad.ACTIVIDAD_UNIVERSIDAD_UOC_ID:
                return Actividad.getUniversidadName(Actividad.ACTIVIDAD_UNIVERSIDAD_UOC_ID, language);
            case Actividad.ACTIVIDAD_UNIVERSIDAD_UAB_ID:
                return Actividad.getUniversidadName(Actividad.ACTIVIDAD_UNIVERSIDAD_UAB_ID, language);
            case Actividad.ACTIVIDAD_UNIVERSIDAD_UPC_ID:
                return Actividad.getUniversidadName(Actividad.ACTIVIDAD_UNIVERSIDAD_UPC_ID, language);
            case Actividad.ACTIVIDAD_UNIVERSIDAD_UPF_ID:
                return Actividad.getUniversidadName(Actividad.ACTIVIDAD_UNIVERSIDAD_UPC_ID, language);
            default:
                return "(-)";
        }

    }

    private void listData() {
        try {
            if (!this.dofilter) {
                this.listFullActividadesData();
            } else {
                this.listFilteredActividadesData();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,
                    language.getProperty("err.sql") + "\n" + language.getProperty("err.detail") + ":\n\n" + ex.getMessage(),
                    language.getProperty("app.title"),
                    JOptionPane.ERROR_MESSAGE);

            // Registra el error en un archivo de LOG
            // Logger.getLogger(FrmResourcesRequest.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            JOptionPane.showMessageDialog(null,
                    language.getProperty("err.rmi") + "\n" + language.getProperty("err.detail") + ":\n\n" + ex.getMessage(),
                    language.getProperty("app.title"),
                    JOptionPane.ERROR_MESSAGE);

            // Registra el error en un archivo de LOG
            // Logger.getLogger(FrmResourcesRequest.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,
                    language.getProperty("err.generic") + "\n" + language.getProperty("err.detail") + ":\n\n" + ex.getMessage(),
                    language.getProperty("app.title"),
                    JOptionPane.ERROR_MESSAGE);

            // Registra el error en un archivo de LOG
            // Logger.getLogger(FrmResourcesRequest.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAsistencia;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JComboBox cboFiltroTipoActividad;
    private javax.swing.JButton cmdClearFilter;
    private javax.swing.JButton cmdClose;
    private javax.swing.JButton cmdFilter;
    private javax.swing.JFormattedTextField fldFiltroDateFin;
    private javax.swing.JFormattedTextField fldFiltroDateIni;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblFiltroDateEnd;
    private javax.swing.JLabel lblFiltroDateIni;
    private javax.swing.JLabel lblFiltroTipoActividad;
    private javax.swing.JTable tblData;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the usuario
     */
    public Usuario getUsuario() {
        return usuario;
    }

    /**
     * @param usuario the usuario to set
     */
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    private void setTipoActividades() {

        if (tiposActividad == null) {
            tiposActividad = new ArrayList<ComboItem>();
        }
        ComboItem cb = new ComboItem(language.getProperty(eAcademiaEU.FORM_PNLACTIVIDAD_TIPO_ACTIVIDAD_SELECCIONA), -1);
        tiposActividad.add(cb);
        tiposActividad.add(new ComboItem(Actividad.getTipoActividadName(Actividad.ACTIVIDAD_TIPO_CONGRESO_ID, language), Actividad.ACTIVIDAD_TIPO_CONGRESO_ID));
        tiposActividad.add(new ComboItem(Actividad.getTipoActividadName(Actividad.ACTIVIDAD_TIPO_JORNADA_ID, language), Actividad.ACTIVIDAD_TIPO_JORNADA_ID));
        tiposActividad.add(new ComboItem(Actividad.getTipoActividadName(Actividad.ACTIVIDAD_TIPO_MASTER_ID, language), Actividad.ACTIVIDAD_TIPO_MASTER_ID));
        tiposActividad.add(new ComboItem(Actividad.getTipoActividadName(Actividad.ACTIVIDAD_TIPO_CONFERENCIA_ID, language), Actividad.ACTIVIDAD_TIPO_CONFERENCIA_ID));
        cboFiltroTipoActividad.removeAll();
        cboFiltroTipoActividad.setModel(new DefaultComboBoxModel(tiposActividad.toArray()));

    }

}
