package edu.uoc.tdp.pac4.client.mantenimiento;

import edu.uoc.tdp.pac4.client.gestion.*;
import edu.uoc.tdp.pac4.beans.Aula;
import edu.uoc.tdp.pac4.beans.Centro;
import edu.uoc.tdp.pac4.eAcademiaEU;
import edu.uoc.tdp.pac4.exceptions.GroupNotEmptyException;
import edu.uoc.tdp.pac4.remote.Mantenimiento;
import edu.uoc.tdp.pac4.util.ComboItem;
import edu.uoc.tdp.pac4.util.LanguageUtils;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.rmi.RemoteException;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**********************************************************************
 ******************** @author JavaBeginers - Cristian******************
 *********************************************************************/
public class PnlMantenimientoAulas extends javax.swing.JDialog 
{
    private Mantenimiento manager;
    private LanguageUtils language;
    private ArrayList<Aula> aulas; 
    private boolean dofilter = false;

public PnlMantenimientoAulas(java.awt.Frame parent, boolean modal, Mantenimiento manager, LanguageUtils language) {
        super(parent, modal); 
        this.language       = language;
        this.manager        = manager;
        initComponents();
        setLocationRelativeTo(null);
        prepararTextos();
        setCombos();
        listarAulas();
      
}

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnClose = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        fldcapacity = new javax.swing.JTextField();
        lblCapacidad = new javax.swing.JLabel();
        btnFilter = new javax.swing.JButton();
        btnClearFilter = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        comboActiva = new javax.swing.JComboBox();
        lblActivas = new javax.swing.JLabel();
        comboCentro = new javax.swing.JComboBox();
        lblCentro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jToolBar1.setRollover(true);

        btnClose.setText("Cerrar");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblData);

        btnAdd.setText("Nuevo");
        btnAdd.setFocusable(false);
        btnAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdd.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnEdit.setText("Editar");
        btnEdit.setFocusable(false);
        btnEdit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEdit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setText("Eliminar");
        btnDelete.setFocusable(false);
        btnDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDelete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        lblCapacidad.setText("Capacidad Mínima");

        btnFilter.setText("Filtrar");
        btnFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilterActionPerformed(evt);
            }
        });

        btnClearFilter.setText("Reestablecer");
        btnClearFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearFilterActionPerformed(evt);
            }
        });

        btnView.setText("Ver");
        btnView.setFocusable(false);
        btnView.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnView.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        lblActivas.setText("Activa");

        lblCentro.setText("Centro");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdd)
                        .addGap(0, 0, 0)
                        .addComponent(btnEdit)
                        .addGap(0, 0, 0)
                        .addComponent(btnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnView)
                        .addGap(140, 140, 140)
                        .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCentro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(comboCentro, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(lblActivas, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboActiva, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(lblCapacidad)
                                .addGap(18, 18, 18)
                                .addComponent(fldcapacity, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(btnClose))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnClearFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnAdd)
                        .addComponent(btnEdit)
                        .addComponent(btnDelete)
                        .addComponent(btnView)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fldcapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCapacidad)
                    .addComponent(comboActiva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblActivas)
                    .addComponent(comboCentro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCentro))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFilter)
                    .addComponent(btnClearFilter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnClose)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

//Establece los textos segun idioma seleccionado      
   private void prepararTextos() {
        this.setTitle(language.getProperty("mantenimiento.aulas.Mantenimiento"));
        this.btnAdd.setText         (language.getProperty("mantenimiento.Nueva"));
        this.btnEdit.setText        (language.getProperty("mantenimiento.Editar"));
        this.btnDelete.setText      (language.getProperty("mantenimiento.Eliminar"));
        this.btnView.setText     (language.getProperty("mantenimiento.Ver"));
        this.lblActivas.setText (language.getProperty("mantenimiento.aulas.Activas"));
        this.lblCapacidad.setText (language.getProperty("mantenimiento.aulas.Capacidadminima"));
        this.lblCentro.setText (language.getProperty("mantenimiento.aulas.Centro"));
                
        this.btnClose.setText       (language.getProperty("mantenimiento.Cerrar"));
        this.btnFilter.setText      (language.getProperty("mantenimiento.Filtrar"));
        this.btnClearFilter.setText (language.getProperty("mantenimiento.Restablecer")); 
        
        this.fldcapacity.setText (language.getProperty("0")); 
        this.fldcapacity.addKeyListener(new KeyAdapter(){
				public void keyTyped(KeyEvent e){
                                    char c= e.getKeyChar();
                                    if (Character.isDigit(c) == false) {
			            e.consume();//Solo permite introducir dígitos
			        }}});
    }
   
//Se escoge 'Alta de Aula'  
   private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
           PnlMantenimientoAulaGestor form = new PnlMantenimientoAulaGestor(null, true ,manager, language, "Add", 0);
           form.setLocationRelativeTo(null);
           form.setVisible(true);
           listarAulas();
   }//GEN-LAST:event_btnAddActionPerformed

//Se escoge 'Edición de Aula'     
   private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
      //No hay  fila seleccionada
      if (tblData.getSelectedRow() < 0)
      {
         JOptionPane.showMessageDialog(null,
                                       language.getProperty("mantenimiento.msg.NoAula"),
                                       language.getProperty("app.title"),
                                       JOptionPane.WARNING_MESSAGE);
         return;
      }

      //Hay fila seleccionada:
      Aula aula = aulas.get(tblData.getSelectedRow());
      PnlMantenimientoAulaGestor form = new PnlMantenimientoAulaGestor(null, true, manager, language, "Edit", aula.getId());
      form.setLocationRelativeTo(null);
      form.setVisible(true);
      listarAulas();
   }//GEN-LAST:event_btnEditActionPerformed

//Cerrar el Formulario
   private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
      this.dispose();
   }//GEN-LAST:event_btnCloseActionPerformed

//Se escoge Desactivar el Aula
   private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
      //No hay fila seleccionada:
      if (tblData.getSelectedRow() < 0)
      {
         JOptionPane.showMessageDialog(null,
                                       language.getProperty("mantenimiento.msg.NoAula"),
                                       language.getProperty("app.title"),
                                       JOptionPane.WARNING_MESSAGE);
         return;
      }
      
      //Hay fila seleccionada:
      
      Aula aula = aulas.get(tblData.getSelectedRow());
      Object[] options = {language.getProperty("mantenimiento.Si"), language.getProperty("mantenimiento.No")};
      
      int reply = JOptionPane.showOptionDialog(this, language.getProperty("mantenimiento.msg.EliminarAula"),
                                               language.getProperty("app.title"), JOptionPane.YES_NO_OPTION, 
                                               JOptionPane.QUESTION_MESSAGE, null, options, aula);
      if (reply == 0) {
      try {
            manager.eliminarAula(aula.getId());

      }
      catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, 
                                          language.getProperty("err.sql") + "\n" + language.getProperty("err.detail") + ":\n\n" + ex.getMessage(), 
                                          language.getProperty("app.title"), 
                                          JOptionPane.ERROR_MESSAGE);
      }
      catch (Exception ex) {
            JOptionPane.showMessageDialog(null, 
                                          language.getProperty("err.rmi") + "\n" + language.getProperty("err.detail") + ":\n\n" + ex.getMessage(), 
                                          language.getProperty("app.title"), 
                                          JOptionPane.ERROR_MESSAGE);
      }
      
      listarAulas();
      }
   }//GEN-LAST:event_btnDeleteActionPerformed
   
//Botón Filtrar
    private void btnFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilterActionPerformed
            this.dofilter = true;
            if(this.fldcapacity.getText().equals("")){
                this.fldcapacity.setText("0");
            }
            listarAulas();
    }//GEN-LAST:event_btnFilterActionPerformed

//Botón Limpiar Filtro
    private void btnClearFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearFilterActionPerformed
        // TODO add your handling code here:
        this.fldcapacity.setText("0");
        this.comboActiva.setSelectedIndex(0);
        this.comboCentro.setSelectedIndex(0);
        this.dofilter = false;
        listarAulas();
    }//GEN-LAST:event_btnClearFilterActionPerformed

//Consultar Aula
    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // No hay fila seleccionada
      if (tblData.getSelectedRow() < 0)
      {
         JOptionPane.showMessageDialog(null,
                                       language.getProperty("mantenimiento.msg.NoAula"),
                                       language.getProperty("app.title"),
                                       JOptionPane.WARNING_MESSAGE);
         return;
      }

      // Hay fila seleccionada:
      Aula aula = aulas.get(tblData.getSelectedRow());

      PnlMantenimientoAulaGestor form = new PnlMantenimientoAulaGestor(null, true, manager, language, "Explore", aula.getId());
      form.setLocationRelativeTo(null);
      form.setVisible(true);
    }//GEN-LAST:event_btnViewActionPerformed

//Carga el Combo de los Centros
  private void setCombos() {
        comboCentro.removeAll();
        List<Centro> centros = new ArrayList<Centro>();
        try {
            centros = manager.getCentros();
        } catch (Exception ex) {
            Logger.getLogger(PnlMantenimientoActividadGestor.class.getName()).log(Level.SEVERE, null, ex);
        }
        comboCentro.addItem(new ComboItem(language.getProperty("mantenimiento.Todos"), 0));
        for(Centro centro: centros) {
        comboCentro.addItem(new ComboItem(centro.getNom(),centro.getId()));
        }  
        comboActiva.addItem(new ComboItem(language.getProperty("mantenimiento.Si"), 0));
        comboActiva.addItem(new ComboItem(language.getProperty("mantenimiento.No"), 1));
        
    }

//Cargar todas las Aulas
    private void todasAulas() throws SQLException, RemoteException, Exception {
        ArrayList<String> header = new ArrayList<String>();   // cabecera
      
        header.add(language.getProperty("mantenimiento.aulas.Codigo"));
        header.add(language.getProperty("mantenimiento.aulas.Nombre"));
        header.add(language.getProperty("mantenimiento.aulas.Capacidad"));
        header.add(language.getProperty("mantenimiento.aulas.Ubicacion"));

        
        String[][] gridData;
        
        aulas = manager.getAulas();
        
        gridData = new String[aulas.size()][4];
        
        int i = 0;
        for (Aula aula : aulas) {
            gridData[i][0] = aula.getCodigo();
            gridData[i][1] = aula.getNombre();
            gridData[i][2] = "" + aula.getCapacidad();
            gridData[i][3] = aula.getUbicacion();
            i++;
        }
        
        this.tblData.setModel(new javax.swing.table.DefaultTableModel(gridData, header.toArray())
            {@Override public boolean isCellEditable(int row, int column)
                { return false; } 
            });
    }
    
//Cargar Aulas Filtradas
    private void filtrarAulas() throws SQLException, RemoteException, Exception {
        ArrayList<String> header = new ArrayList<String>();   // cabecera
      
        header.add(language.getProperty("mantenimiento.aulas.Codigo"));
        header.add(language.getProperty("mantenimiento.aulas.Nombre"));
        header.add(language.getProperty("mantenimiento.aulas.Capacidad"));
        header.add(language.getProperty("mantenimiento.aulas.Ubicacion"));

        String[][] gridData;
        if (comboActiva.getSelectedIndex()==0){
        aulas = manager.getAulas();
        }else{
            aulas=manager.getAulasInactivas();
        }
        gridData = new String[aulas.size()][4];
        int i = 0;
        for (Aula aula : aulas) {
            if (new Integer(this.fldcapacity.getText()) <= aula.getCapacidad()) {
                if(comboCentro.getSelectedIndex()==0){
            gridData[i][0] = "" + aula.getCodigo();
            gridData[i][1] = aula.getNombre();
            gridData[i][2] = "" + aula.getCapacidad();
            gridData[i][3] = aula.getUbicacion();
            i++;
                } else{
                    if(aula.getCentro()==((ComboItem)comboCentro.getSelectedItem()).getId()){
                             gridData[i][0] = "" + aula.getCodigo();
                             gridData[i][1] = aula.getNombre();
                             gridData[i][2] = "" + aula.getCapacidad();
                             gridData[i][3] = aula.getUbicacion();
                             i++;
                    }
                }
            }
        }
        
        this.tblData.setModel(new javax.swing.table.DefaultTableModel(gridData, header.toArray())
            {@Override public boolean isCellEditable(int row, int column)
                { return false; } 
            });
    }
 
//filtrar si el filtro esta activo. Mostrar todas en caso contrario
   private void listarAulas()
   {
      try {
            if(comboActiva.getSelectedIndex()==1){
                this.btnDelete.setEnabled(false);
                this.btnEdit.setEnabled(false);
            }else{
                this.btnDelete.setEnabled(true);
                this.btnEdit.setEnabled(true);  
            }
          if (!this.dofilter) {
              this.todasAulas();
              comboActiva.setSelectedIndex(0);
              comboCentro.setSelectedIndex(0);
          }
          else {
              this.filtrarAulas();
          }
      } 
      catch (SQLException ex)
      {
         JOptionPane.showMessageDialog(null, 
                                       language.getProperty("err.sql") + "\n" + language.getProperty("err.detail") + ":\n\n" + ex.getMessage(), 
                                       language.getProperty("app.title"), 
                                       JOptionPane.ERROR_MESSAGE);
      }
      catch (RemoteException ex)
      {
         JOptionPane.showMessageDialog(null, 
                                       language.getProperty("err.rmi") + "\n" + language.getProperty("err.detail") + ":\n\n" + ex.getMessage(), 
                                       language.getProperty("app.title"), 
                                       JOptionPane.ERROR_MESSAGE);
      }
      catch (Exception ex) 
      {
         JOptionPane.showMessageDialog(null, 
                                       language.getProperty("err.generic") + "\n" + language.getProperty("err.detail") + ":\n\n" + ex.getMessage(), 
                                       language.getProperty("app.title"), 
                                       JOptionPane.ERROR_MESSAGE);
      }
   }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClearFilter;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnFilter;
    private javax.swing.JButton btnView;
    private javax.swing.JComboBox comboActiva;
    private javax.swing.JComboBox comboCentro;
    private javax.swing.JTextField fldcapacity;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblActivas;
    private javax.swing.JLabel lblCapacidad;
    private javax.swing.JLabel lblCentro;
    private javax.swing.JTable tblData;
    // End of variables declaration//GEN-END:variables
}
