/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.uoc.tdp.pac4.client.conexion;
import edu.uoc.tdp.pac4.util.LanguageUtils;
import edu.uoc.tdp.pac4.beans.Grupo;
import javax.swing.JOptionPane;
import java.io.IOException;
import javax.swing.event.HyperlinkEvent;
import javax.swing.event.HyperlinkListener;
import java.net.URL;

/**
 *
 * @author JavaBegines
 */
public class PnlMuestraPlanDocente extends javax.swing.JDialog implements HyperlinkListener  {

    private Grupo grupo;
    private LanguageUtils language;    
    /**
     * Creates new form PnlMuestraPlanDocente
     */
    public PnlMuestraPlanDocente(PnlSolicitaMatricula parent, boolean modal, LanguageUtils language, Grupo grupo) {
        super(parent, modal);
        this.language = language;
        this.grupo = grupo;  
        initComponents();             
        inicializaEditorPanes();        
    }

    private void inicializaEditorPanes()
    {
        
        this.setTitle(language.getProperty("cnxmatricula.plandocente.title") + grupo.getNombreActividad()); //NOI18N
        jEdtPanePlanDocente.setContentType("text/html"); 
        jEdtPaneInfoOnline.setContentType("text/html"); 
//        jEdtPanePlanDocente.setText(grupo.getPlanDocenteCurso());
        jEdtPanePlanDocente.addHyperlinkListener(this);
        jEdtPaneInfoOnline.addHyperlinkListener(this);
        tabPlanDocente.setTitleAt(0, language.getProperty("cnxmatricula.plandocente.tabplandocente"));
        tabPlanDocente.setTitleAt(1, language.getProperty("cnxmatricula.plandocente.tabinfoonline"));
        tabPlanDocente.setToolTipText(null);
        tabPlanDocente.setToolTipTextAt(0, language.getProperty("cnxmatricula.plandocente.tooltipinternet")); 
        tabPlanDocente.setToolTipTextAt(1, language.getProperty("cnxmatricula.plandocente.tooltipinternet2"));
        jEdtPanePlanDocente.setCaretPosition(0);
        
        try {
            jEdtPaneInfoOnline.setPage("http://es.wikipedia.org/w/index.php?search=" + 
                                        grupo.getNombreActividad().replaceAll("\\s", "+"));                                    
        }
        catch (IOException ex) {
            
            //NOI18N
            JOptionPane.showMessageDialog(null, 
                language.getProperty("err.generic") + "\n" + language.getProperty("err.detail") + ":\n\n" + ex.getMessage(), 
                language.getProperty("app.title"), 
                JOptionPane.ERROR_MESSAGE);
        }
        catch (Exception ex) 
        {
             JOptionPane.showMessageDialog(null, 
                language.getProperty("err.generic") + "\n" + language.getProperty("err.detail") + ":\n\n" + ex.getMessage(), 
                language.getProperty("app.title"), 
                JOptionPane.ERROR_MESSAGE);
        }
        
    }
    
    @Override
    public void hyperlinkUpdate(HyperlinkEvent event) {
        if (event.getEventType() == HyperlinkEvent.EventType.ACTIVATED) {
            try {
                
                if (tabPlanDocente.getSelectedIndex() == 0)
                    jEdtPanePlanDocente.setPage(event.getURL());
                else
                    jEdtPaneInfoOnline.setPage(event.getURL());
                
            }catch (IOException ex) {
                
                //NOI18N
                JOptionPane.showMessageDialog(null, 
                    language.getProperty("err.generic") + "\n" + language.getProperty("err.detail") + ":\n\n" + ex.getMessage(), 
                    language.getProperty("app.title"), 
                    JOptionPane.ERROR_MESSAGE);
                
            }catch (Exception ex)
            {
                //NOI18N
                JOptionPane.showMessageDialog(null, 
                    language.getProperty("err.generic") + "\n" + language.getProperty("err.detail") + ":\n\n" + ex.getMessage(), 
                    language.getProperty("app.title"), 
                    JOptionPane.ERROR_MESSAGE);
            }
    }
  }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmdCerrar = new javax.swing.JButton();
        tabPlanDocente = new javax.swing.JTabbedPane();
        jScrlPanePlanDocente = new javax.swing.JScrollPane();
        jEdtPanePlanDocente = new javax.swing.JEditorPane();
        jScrlPaneOnline = new javax.swing.JScrollPane();
        jEdtPaneInfoOnline = new javax.swing.JEditorPane();
        cmdRecargar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        cmdCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/arrow-curve-180.png"))); // NOI18N
        cmdCerrar.setText(language.getProperty("cnxmatricula.plandocente.cerrar"));
        cmdCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCerrarActionPerformed(evt);
            }
        });

        tabPlanDocente.setToolTipText("");

        jEdtPanePlanDocente.setEditable(false);
        jScrlPanePlanDocente.setViewportView(jEdtPanePlanDocente);

        tabPlanDocente.addTab("Plan Docente", jScrlPanePlanDocente);

        jEdtPaneInfoOnline.setEditable(false);
        jScrlPaneOnline.setViewportView(jEdtPaneInfoOnline);

        tabPlanDocente.addTab("Información Online", jScrlPaneOnline);

        cmdRecargar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/web-slice.png"))); // NOI18N
        cmdRecargar.setText(language.getProperty("cnxmatricula.plandocente.reload"));
        cmdRecargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRecargarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cmdRecargar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmdCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(tabPlanDocente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabPlanDocente, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdRecargar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_cmdCerrarActionPerformed

    private void cmdRecargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRecargarActionPerformed
        inicializaEditorPanes();
    }//GEN-LAST:event_cmdRecargarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdCerrar;
    private javax.swing.JButton cmdRecargar;
    private javax.swing.JEditorPane jEdtPaneInfoOnline;
    private javax.swing.JEditorPane jEdtPanePlanDocente;
    private javax.swing.JScrollPane jScrlPaneOnline;
    private javax.swing.JScrollPane jScrlPanePlanDocente;
    private javax.swing.JTabbedPane tabPlanDocente;
    // End of variables declaration//GEN-END:variables
}
