package edu.uoc.tdp.pac4.client.conexion;

import edu.uoc.tdp.pac4.beans.Curso;
import edu.uoc.tdp.pac4.beans.Grupo;
import edu.uoc.tdp.pac4.beans.Usuario;
import edu.uoc.tdp.pac4.exceptions.StudentAssistanceAlreadyCountedException;
import edu.uoc.tdp.pac4.remote.Conexion;
import edu.uoc.tdp.pac4.util.ComboItem;
import edu.uoc.tdp.pac4.util.LanguageUtils;
import java.rmi.RemoteException;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author eSupport Netbeans
 */
public class PnlMarcaAsistencia extends javax.swing.JDialog 
{
   private Conexion manager;
   private LanguageUtils language;
   private ArrayList<Grupo> grupos;
   private Usuario alumno;

   /**
    * Creates new form PnlSolicitaMatricula
    */
   public PnlMarcaAsistencia(java.awt.Frame parent, boolean modal, Conexion manager, LanguageUtils language, Usuario alumno) 
   {
      super(parent, modal);
      this.manager = manager;
      this.language = language;
      this.alumno = alumno;  
      initComponents();      
      setLocationRelativeTo(null);
      pnlFilter.setVisible(false);            
      fillForm();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tlbarMatriculas = new javax.swing.JToolBar();
        cmdAdd = new javax.swing.JButton();
        jSprtMatriculas = new javax.swing.JToolBar.Separator();
        jSprtMatriculas2 = new javax.swing.JToolBar.Separator();
        cmdFilter = new javax.swing.JToggleButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        lblHoy = new javax.swing.JLabel();
        cmdClose = new javax.swing.JButton();
        scrlPnCursos = new javax.swing.JScrollPane();
        tblGrupos = new javax.swing.JTable();
        pnlFilter = new javax.swing.JPanel();
        lblTurno = new javax.swing.JLabel();
        lblCurso = new javax.swing.JLabel();
        cboCurso = new javax.swing.JComboBox();
        cmdSetFilter = new javax.swing.JButton();
        cboTurno = new javax.swing.JComboBox();
        cmdFilterDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(language.getProperty("cnxmatricula.marcarasistencia.title"));
        setName("frmMatriculas"); // NOI18N

        tlbarMatriculas.setRollover(true);

        cmdAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/chair--plus.png"))); // NOI18N
        cmdAdd.setText(language.getProperty("cnxmatricula.marcarasistencia.asistir"));
        cmdAdd.setFocusable(false);
        cmdAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmdAdd.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cmdAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAddActionPerformed(evt);
            }
        });
        tlbarMatriculas.add(cmdAdd);
        tlbarMatriculas.add(jSprtMatriculas);
        tlbarMatriculas.add(jSprtMatriculas2);

        cmdFilter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/funnel.png"))); // NOI18N
        cmdFilter.setText(language.getProperty("cnxmatricula.marcarasistencia.filtrar"));
        cmdFilter.setFocusable(false);
        cmdFilter.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmdFilter.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cmdFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdFilterActionPerformed(evt);
            }
        });
        tlbarMatriculas.add(cmdFilter);
        tlbarMatriculas.add(jSeparator3);
        tlbarMatriculas.add(jSeparator4);

        lblHoy.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblHoy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/clock-frame.png"))); // NOI18N
        lblHoy.setText(language.getProperty("cnxmatricula.marcarasistencia.hoy"));
        tlbarMatriculas.add(lblHoy);

        cmdClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/arrow-curve-180.png"))); // NOI18N
        cmdClose.setText(language.getProperty("cnxmatricula.marcarasistencia.cerrar"));
        cmdClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCloseActionPerformed(evt);
            }
        });

        tblGrupos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrlPnCursos.setViewportView(tblGrupos);

        pnlFilter.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblTurno.setText(language.getProperty("cnxmatricula.marcarasistencia.turno"));

        lblCurso.setText(language.getProperty("cnxmatricula.marcarasistencia.curso"));

        cmdSetFilter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/funnel--plus.png"))); // NOI18N
        cmdSetFilter.setText(language.getProperty("cnxmatricula.marcarasistencia.aplicar"));
        cmdSetFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSetFilterActionPerformed(evt);
            }
        });

        cmdFilterDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/eraser.png"))); // NOI18N
        cmdFilterDelete.setText(language.getProperty("cnxmatricula.marcarasistencia.limpiar"));
        cmdFilterDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdFilterDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFilterLayout = new javax.swing.GroupLayout(pnlFilter);
        pnlFilter.setLayout(pnlFilterLayout);
        pnlFilterLayout.setHorizontalGroup(
            pnlFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFilterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCurso)
                    .addComponent(lblTurno))
                .addGap(18, 18, 18)
                .addGroup(pnlFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFilterLayout.createSequentialGroup()
                        .addComponent(cboCurso, 0, 436, Short.MAX_VALUE)
                        .addGap(215, 215, 215))
                    .addGroup(pnlFilterLayout.createSequentialGroup()
                        .addComponent(cboTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 411, Short.MAX_VALUE)))
                .addGroup(pnlFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmdSetFilter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmdFilterDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlFilterLayout.setVerticalGroup(
            pnlFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFilterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFilterLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnlFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCurso)))
                    .addComponent(cmdFilterDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTurno)
                    .addComponent(cboTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdSetFilter))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tlbarMatriculas, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cmdClose))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrlPnCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(pnlFilter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tlbarMatriculas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(pnlFilter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrlPnCursos, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdClose)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   /**
    * Añade una solicitud de matrícula
    * @param evt 
    */
   private void cmdAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAddActionPerformed
    
        if (tblGrupos.getSelectedRow() < 0) {
        
            
            JOptionPane.showMessageDialog(null,
                                          language.getProperty("cnxmatricula.marcarasistencia.warnasistencia"),
                                          language.getProperty("app.title"),
                                          JOptionPane.WARNING_MESSAGE);
         return;
        }
                
        // Obtiene el curso seleccionado, para obtener sus datos
        Grupo grupo = grupos.get(tblGrupos.getSelectedRow()); 
       
        if (grupo.getAsistenciaAbierta() == Grupo.PERIODO_CERRADO) {
        
   
            JOptionPane.showMessageDialog(null,
                                          language.getProperty("cnxmatricula.marcarasistencia.warncerrado"),
                                          language.getProperty("app.title"),
                                          JOptionPane.WARNING_MESSAGE);
         return;
        }
        
        try 
        {
            
            //Para poder insertar el registro de asistencia necesitamos saber el id de la 
            //última asistencia registrada para dicho grupo, necesitamos consultarlo explicitamente.
            manager.addAsistenciaAlumno(manager.getLastAssistance(grupo.getId()).getId(), alumno.getId());            
            JOptionPane.showMessageDialog(null,
                                          language.getProperty("cnxmatricula.marcarasistencia.infoasistencia"),
                                          language.getProperty("app.title"),
                                          JOptionPane.INFORMATION_MESSAGE);
            
        }
        catch (SQLException ex)
        {
            JOptionPane.showMessageDialog(null,
                                          "ERROR SQL: " + ex.getMessage(),
                                          language.getProperty("app.title"),
                                          JOptionPane.ERROR_MESSAGE);
        }
        catch (StudentAssistanceAlreadyCountedException ex)
        {            
            JOptionPane.showMessageDialog(null,
                                          language.getProperty("cnxmatricula.marcarasistencia.errorasistenciagrupo"),
                                          language.getProperty("app.title"),
                                          JOptionPane.ERROR_MESSAGE);
        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(null,
                                          "ERROR: " + ex.getMessage(),
                                          language.getProperty("app.title"),
                                          JOptionPane.ERROR_MESSAGE);
        }
        fillForm();
    
   }//GEN-LAST:event_cmdAddActionPerformed

   private void cmdCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCloseActionPerformed

      // Cierra el formulario
      this.dispose();

   }//GEN-LAST:event_cmdCloseActionPerformed

    private void cmdSetFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSetFilterActionPerformed

        int idCurso = (cboCurso.getSelectedIndex() >= 0 ? ((Curso)cboCurso.getSelectedItem()).getId() : -1);
        int idTurno = (cboTurno.getSelectedIndex() >= 0 ? ((ComboItem)cboTurno.getSelectedItem()).getId() : -1);

        fillForm(idCurso, idTurno);
    }//GEN-LAST:event_cmdSetFilterActionPerformed

    private void cmdFilterDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdFilterDeleteActionPerformed

        //Limpiar filtros y recargar tabla
        fillFilterPanel();
        fillForm();

    }//GEN-LAST:event_cmdFilterDeleteActionPerformed

    private void cmdFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdFilterActionPerformed
      
      pnlFilter.setVisible(cmdFilter.isSelected());
      
      // Si se oculta el filtro, se regenera la lista completa
      if (!pnlFilter.isVisible())
      {
         fillForm();
      }
      else
      {
         fillFilterPanel();
      }
    }//GEN-LAST:event_cmdFilterActionPerformed

  
  /**
    * Rellena el panel de filtros.
    */
   private void fillFilterPanel() 
   {
      try 
      {
                
         // Rellena la lista de cursos
         cboCurso.removeAll();
         cboCurso.setModel(new DefaultComboBoxModel(manager.getCursos().toArray()));
         cboCurso.setSelectedIndex(-1);

         // Rellena el combo de filtros
         ArrayList<ComboItem> turnos = new ArrayList<ComboItem>();
         turnos.add(new ComboItem(Grupo.getTurnoName(Grupo.TURNO_MANANA, language), Grupo.TURNO_MANANA));
         turnos.add(new ComboItem(Grupo.getTurnoName(Grupo.TURNO_TARDE, language), Grupo.TURNO_TARDE));
         cboTurno.removeAll();
         cboTurno.setModel(new DefaultComboBoxModel(turnos.toArray()));
         cboTurno.setSelectedIndex(-1);                  
      } 
      catch (Exception ex) 
      {
         JOptionPane.showMessageDialog(null, 
                                       language.getProperty("err.filter"), 
                                       language.getProperty("app.title"), 
                                       JOptionPane.ERROR_MESSAGE);
      }
   }
   
   /**
    * Confecciona el listado completo.
    */
   private void fillForm()
   {
      //Por defecto, solo muestra los cursos cuya fecha de comienzo sea posterior a la actual 
      fillForm(-1, -1);
   }
   
   /**
    * Confecciona el listado filtrado.
    */
   private void fillForm(int idCurso, int idTurno)
   {
      
      SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");                                
      lblHoy.setText(language.getProperty("cnxmatricula.marcarasistencia.hoy")  + df.format(new Date()));
        
      // Rellena la tabla
      ArrayList<String> header = new ArrayList<String>();   // cabecera
      header.add(language.getProperty("cnxmatricula.marcarasistencia.tableheadergrupo"));
      header.add(language.getProperty("cnxmatricula.marcarasistencia.tableheadercurso"));
      header.add(language.getProperty("cnxmatricula.marcarasistencia.tableheaderprofesor"));
      header.add(language.getProperty("cnxmatricula.marcarasistencia.tableheaderaula"));
      header.add(language.getProperty("cnxmatricula.marcarasistencia.tableheaderturno"));
      header.add(language.getProperty("cnxmatricula.marcarasistencia.tableheaderiniciocurso"));
      header.add(language.getProperty("cnxmatricula.marcarasistencia.tableheadermarcajeasistencia"));      
      
      String[][] gridData;
      ArrayList<String> row;

      try 
      {
         grupos = manager.getGruposByMatricula(alumno.getId(), idCurso, idTurno);
         gridData = new String[grupos.size()][7];
         int i = 0;
         for (Grupo grupo : grupos)
         {
            gridData[i][0] = grupo.getNombre();
            gridData[i][1] = grupo.getNombreCurso();
            gridData[i][2] = grupo.getNombreProfesor();
            gridData[i][3] = grupo.getNombreAula();
            gridData[i][4] = (grupo.getTurno() == Grupo.TURNO_MANANA ? "Mañana" : "Tarde");
            gridData[i][5] = (grupo.getFechaInicioCurso() == null ? "?" : df.format(grupo.getFechaInicioCurso()));            
            gridData[i][6] = (grupo.getAsistenciaAbierta() == Grupo.PERIODO_ABIERTO ? "Abierto" : "Cerrado");
            i++;
         }
         
        //Modificamos la tabla para que no sea editable
        tblGrupos.setModel(new DefaultTableModel(gridData, header.toArray()) {
               @Override
               public boolean isCellEditable(int row, int column) {
                    return false;
                }
            });         
         
      } 
      catch (SQLException ex)
      {
         JOptionPane.showMessageDialog(null, 
                                       language.getProperty("err.sql") + "\n" + language.getProperty("err.detail") + ":\n\n" + ex.getMessage(), 
                                       language.getProperty("app.title"), 
                                       JOptionPane.ERROR_MESSAGE);
         
         // Registra el error en un archivo de LOG
         // Logger.getLogger(FrmResourcesRequest.class.getName()).log(Level.SEVERE, null, ex);
      }
      catch (RemoteException ex)
      {
         JOptionPane.showMessageDialog(null, 
                                       language.getProperty("err.rmi") + "\n" + language.getProperty("err.detail") + ":\n\n" + ex.getMessage(), 
                                       language.getProperty("app.title"), 
                                       JOptionPane.ERROR_MESSAGE);
         
         // Registra el error en un archivo de LOG
         // Logger.getLogger(FrmResourcesRequest.class.getName()).log(Level.SEVERE, null, ex);
      }
      catch (StudentAssistanceAlreadyCountedException ex)
      {         
         JOptionPane.showMessageDialog(null,
                                       language.getProperty("cnxmatricula.marcarasistencia.errorasistencia"), 
                                       language.getProperty("app.title"),
                                       JOptionPane.ERROR_MESSAGE);
      }
      catch (Exception ex) 
      {
         JOptionPane.showMessageDialog(null, 
                                       language.getProperty("err.generic") + "\n" + language.getProperty("err.detail") + ":\n\n" + ex.getMessage(), 
                                       language.getProperty("app.title"), 
                                       JOptionPane.ERROR_MESSAGE);
         
         // Registra el error en un archivo de LOG
         // Logger.getLogger(FrmResourcesRequest.class.getName()).log(Level.SEVERE, null, ex);
      }
   }
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cboCurso;
    private javax.swing.JComboBox cboTurno;
    private javax.swing.JButton cmdAdd;
    private javax.swing.JButton cmdClose;
    private javax.swing.JToggleButton cmdFilter;
    private javax.swing.JButton cmdFilterDelete;
    private javax.swing.JButton cmdSetFilter;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSprtMatriculas;
    private javax.swing.JToolBar.Separator jSprtMatriculas2;
    private javax.swing.JLabel lblCurso;
    private javax.swing.JLabel lblHoy;
    private javax.swing.JLabel lblTurno;
    private javax.swing.JPanel pnlFilter;
    private javax.swing.JScrollPane scrlPnCursos;
    private javax.swing.JTable tblGrupos;
    private javax.swing.JToolBar tlbarMatriculas;
    // End of variables declaration//GEN-END:variables
}
